# Generated by Django 6.0.2 on 2026-02-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_telegram_fields_authcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
