# Generated by Django 6.0.2 on 2026-03-08 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keypro', '0005_courseenrollment_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={'ordering': ('-enrolled_at',)},
        ),
    ]
