# Generated by Django 6.0.2 on 2026-03-08 11:08

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def deduplicate_completions(apps, schema_editor):
    """Keep only the row with the highest id for each
    (user, assignment) pair."""
    CompletedAssignment = apps.get_model(
        "keypro", "CompletedAssignment"
    )
    duplicates = (
        CompletedAssignment.objects.values(
            "user", "assignment"
        )
        .annotate(max_id=models.Max("id"), cnt=models.Count("id"))
        .filter(cnt__gt=1)
    )
    for dup in duplicates:
        CompletedAssignment.objects.filter(
            user=dup["user"],
            assignment=dup["assignment"],
        ).exclude(id=dup["max_id"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("keypro", "0006_alter_courseenrollment_options"),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="completedassignment",
            name="action_type",
            field=models.CharField(
                choices=[("complete", "Complete")],
                default="complete",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="completedassignment",
            name="average_speed",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Average typing speed (chars/min)",
            ),
        ),
        migrations.AddField(
            model_name="completedassignment",
            name="mistakes_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="completedassignment",
            name="completed_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
            ),
        ),
        migrations.RemoveField(
            model_name="completedassignment",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="completedassignment",
            name="error_count",
        ),
        migrations.RunPython(
            deduplicate_completions,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="completedassignment",
            constraint=models.UniqueConstraint(
                fields=("user", "assignment"),
                name="unique_user_assignment_completion",
            ),
        ),
    ]
