# Generated by Django 6.0.2 on 2026-03-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keypro', '0007_remove_completedassignment_duration_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['lesson', 'is_active'], name='assignment_lesson_active'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'is_active'], name='lesson_course_active'),
        ),
    ]
